[package]
name = "hello_world"
version = "0.1.0"
authors = ["Michael Heinrich <michael.heinrich@outlook.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
